import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import { DataProvider } from "@/context/ThemeContext";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Exploring Munnar",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
